export const AUTH_USER = 'auth_user';
export const AUTH_ERROR = 'auth_error';
export const CONFIRM_USER_EMAIL = 'confirm_user_email';
export const FORGOT_PASSWORD_EMAIL = 'forgot_password_email';

export const CURRENT_USER = 'current_user';
export const CURRENT_USER_ERROR = 'current_user_error';

export const HSE_ARTICLE_ERROR = 'hse_article_error';

export const HSE_FETCH_ARTICLE = 'hse_fetch_article';
export const HSE_FETCH_ARTICLE_ERROR = 'hse_fetch_article_error';
export const HSE_CREATE_ARTICLE = 'hse_create_article';
export const HSE_CREATE_ARTICLE_ERROR = 'hse_create_article_error';
export const HSE_CREATE_BATCHFILE = 'hse_create_batchfile';
export const HSE_CREATE_BATCHFILE_ERROR = 'hse_create_batchfile_error';

export const HSE_DELETE_ARTICLE = 'delete_hse_article';

export const SSE_ARTICLE_ERROR = 'sse_article_error';

export const SSE_FETCH_ARTICLE = 'sse_fetch_article';
export const SSE_FETCH_ARTICLE_ERROR = 'sse_fetch_article_error';
export const SSE_CREATE_ARTICLE = 'sse_create_article';
export const SSE_CREATE_ARTICLE_ERROR = 'sse_create_article_error';
export const SSE_CREATE_BATCHFILE = 'sse_create_batchfile';
export const SSE_CREATE_BATCHFILE_ERROR = 'sse_create_batchfile_error';

export const SSE_DELETE_ARTICLE = 'delete_sse_article';

// HSE PENDING QUEUE
export const HSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_JUNIOR_FILTER = 'hse_pending_eligibility_filters_article_assign_junior_filter';
export const HSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_JUNIOR_FILTER_ERROR = 'hse_pending_eligibility_filters_article_assign_junior_filter_error';

export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_JUNIOR_APPRAISER = 'hse_pending_quality_appraisals_article_assign_junior_appraiser';
export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_JUNIOR_APPRAISER_ERROR = 'hse_pending_quality_appraisals_article_assign_junior_appraiser_error';

export const HSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_SENIOR_FILTER = 'hse_pending_eligibility_filters_article_assign_seniorfilter';
export const HSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_SENIOR_FILTER_ERROR = 'hse_pending_eligibility_filters_article_assign_seniorfilter_error';

export const HSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_QUEUE = 'hse_pending_eligibility_filters_article_queue';
export const HSE_PENDING_ELIGIBILITY_FILTERS_BATCHFILE_QUEUE = 'hse_pending_eligibility_filters_batchfile_queue';

export const HSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_QUEUE_ERROR = 'hse_pending_eligibility_filters_article_queue_error';
export const HSE_PENDING_ELIGIBILITY_FILTERS_BATCHFILE_QUEUE_ERROR = 'hse_pending_eligibility_filters_batchfile_queue_error';

export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_JUNIOR_FILTER = 'hse_pending_quality_appraisals_article_assign_junior_filter';
export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_JUNIOR_FILTER_ERROR = 'hse_pending_quality_appraisals_article_assign_junior_filter_error';

export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_SENIOR_FILTER = 'hse_pending_quality_appraisals_article_assign_senior_filter';
export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_SENIOR_FILTER_ERROR = 'hse_pending_quality_appraisals_article_assign_senior_filter_error';

export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_QUEUE = 'hse_pending_quality_appraisals_article_queue';
export const HSE_PENDING_QUALITY_APPRAISALS_ARTICLE_QUEUE_ERROR = 'hse_pending_quality_appraisals_article_queue_error';

export const HSE_PENDING_QUALITY_APPRAISALS_BATCHFILE_QUEUE = 'hse_pending_quality_appraisals_batchfile_queue';
export const HSE_PENDING_QUALITY_APPRAISALS_BATCHFILE_QUEUE_ERROR = 'hse_pending_quality_appraisals_batchfile_queue_error';
             
export const HSE_PENDING_LINKING_STUDIES_QUEUE = 'hse_pending_linking_studies_queue';
export const HSE_PENDING_LINKING_STUDIES_QUEUE_ERROR = 'hse_pending_linking_studies_queue_error';

export const HSE_PENDING_PRESENTATION_DETAILS_QUEUE = 'hse_pending_presentation_details_queue';
export const HSE_PENDING_PRESENTATION_DETAILS_QUEUE_ERROR = 'hse_pending_presentation_details_queue_error';


// HSE ASSIGNED QUEUE
export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_QUEUE = 'hse_assigned_eligibility_filters_article_queue';
export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_QUEUE_ERROR = 'hse_assigned_eligibility_filters_article_queue_error';

export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT = 'hse_assigned_eligibility_filters_arcticle_edit';
export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT_ERROR = 'hse_assigned_eligibility_filters_edit_error';

export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_EDIT = 'hse_assigned_quality_appraisals_arcticle_edit';
export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_EDIT_ERROR = 'hse_assigned_quality_appraisals_edit_error';

export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT_COMPLETE = 'hse_assigned_eligibility_filters_edit_complete';
export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT_COMPLETE_ERROR = 'hse_assigned_eligibility_filters_edit_complete_error';

export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_EDIT_COMPLETE = 'hse_assigned_quality_appraisals_edit_complete';
export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_EDIT_COMPLETE_ERROR = 'hse_assigned_quality_appraisals_edit_complete_error';

export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_FETCH = 'hse_assigned_eligibility_filters_article_fetch';
export const HSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_FETCH_ERROR = 'hse_assigned_eligibility_filters_article_fetch_error';

export const HSE_ASSIGNED_QUALITY_APPRAISAL_QUEUE = 'hse_assigned_quality_appraisal_article_queue';
export const HSE_ASSIGNED_QUALITY_APPRAISAL_QUEUE_ERROR = 'hse_assigned_quality_appraisal_article_queue_error';

export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_QUEUE = 'hse_assigned_quality_appraisals_article_queue';
export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_QUEUE_ERROR = 'hse_assigned_quality_appraisals_article_queue_error';

export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_FETCH = 'hse_assigned_quality_appraisals_article_fetch';
export const HSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_FETCH_ERROR = 'hse_assigned_quality_appraisals_article_fetch_error';

export const HSE_ASSIGNED_LINKING_STUDIES_QUEUE = 'hse_assigned_linking_studies_queue';
export const HSE_ASSIGNED_LINKING_STUDIES_QUEUE_ERROR = 'hse_assigned_linking_studies_queue_error';

export const HSE_ASSIGNED_PRESENTATION_DETAILS_QUEUE = 'hse_assigned_presentation_details_queue';
export const HSE_ASSIGNED_PRESENTATION_DETAILS_QUEUE_ERROR = 'hse_assigned_presentation_details_queue_error';


// SSE PENDING QUEUE
export const SSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_JUNIOR_FILTER = 'sse_pending_eligibility_filters_article_assign_junior_filter';
export const SSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_JUNIOR_FILTER_ERROR = 'sse_pending_eligibility_filters_article_assign_junior_filter_error';

export const SSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_SENIOR_FILTER = 'sse_pending_eligibility_filters_article_assign_senior_filter';
export const SSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_ASSIGN_SENIOR_FILTER_ERROR = 'sse_pending_eligibility_filters_article_assign_senior_filter_error';

export const SSE_PENDING_QUALITY_APPRAISALS_ARTICLE_QUEUE = 'sse_pending_quality_appraisals_article_queue';
export const SSE_PENDING_QUALITY_APPRAISALS_BATCHFILE_QUEUE = 'sse_pending_quality_appraisals_batchfile_queue';

export const SSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_QUEUE = 'sse_pending_eligibility_filters_article_queue';
export const SSE_PENDING_ELIGIBILITY_FILTERS_BATCHFILE_QUEUE = 'sse_pending_eligibility_filters_batchfile_queue';

export const SSE_PENDING_ELIGIBILITY_FILTERS_ARTICLE_QUEUE_ERROR = 'sse_pending_eligibility_filters_article_queue_error';
export const SSE_PENDING_ELIGIBILITY_FILTERS_BATCHFILE_QUEUE_ERROR = 'sse_pending_eligibility_filters_batchfile_queue_error';

export const SSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_JUNIOR_FILTER = 'sse_pending_quality_appraisals_article_assign_junior_filter';
export const SSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_JUNIOR_FILTER_ERROR = 'sse_pending_quality_appraisals_article_assign_junior_filter_error';

export const SSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_SENIOR_FILTER = 'sse_pending_eligibility_filters_article_assign_senior_filter';
export const SSE_PENDING_QUALITY_APPRAISALS_ARTICLE_ASSIGN_SENIOR_FILTER_ERROR = 'sse_pending_eligibility_filters_article_assign_senior_filter_error';

export const SSE_PENDING_QUALITY_APPRAISALS_ARTICLE_QUEUE_ERROR = 'sse_pending_quality_appraisals_article_queue_error';
export const SSE_PENDING_QUALITY_APPRAISALS_BATCHFILE_QUEUE_ERROR = 'sse_pending_quality_appraisals_batchfile_queue_error';

export const SSE_PENDING_QUALITY_APPRAISALS_QUEUE = 'sse_pending_quality_appraisal_queue';
export const SSE_PENDING_QUALITY_APPRAISALS_QUEUE_ERROR = 'sse_pending_quality_appraisal_queue_error';

export const SSE_PENDING_LINKING_STUDIES_QUEUE = 'sse_pending_linking_studies_queue';
export const SSE_PENDING_LINKING_STUDIES_QUEUE_ERROR = 'sse_pending_linking_studies_queue_error';

export const SSE_PENDING_PRESENTATION_DETAILS_QUEUE = 'sse_pending_presentation_details_queue';
export const SSE_PENDING_PRESENTATION_DETAILS_QUEUE_ERROR = 'sse_pending_presentation_details_queue_error';


// SSE ASSIGNED QUEUE
export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_QUEUE = 'sse_assigned_eligibility_filters_queue';
export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_QUEUE_ERROR = 'sse_assigned_eligibility_filters_queue_error';

export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT = 'sse_assigned_eligibility_filters_edit';
export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT_ERROR = 'sse_assigned_eligibility_filters_edit_error';

export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT_COMPLETE = 'sse_assigned_eligibility_filters_edit_complete';
export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_EDIT_COMPLETE_ERROR = 'sse_assigned_eligibility_filters_edit_complete_error';

export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_FETCH = 'sse_assigned_eligibility_filters_article_fetch';
export const SSE_ASSIGNED_ELIGIBILITY_FILTERS_ARTICLE_FETCH_ERROR = 'sse_assigned_eligibility_filters_article_fetch_error';

export const SSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_QUEUE = 'sse_assigned_quality_appraisals_queue';
export const SSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_QUEUE_ERROR = 'sse_assigned_quality_appraisals_queue_error';

export const SSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_FETCH = 'sse_assigned_quality_appraisals_article_fetch';
export const SSE_ASSIGNED_QUALITY_APPRAISALS_ARTICLE_FETCH_ERROR = 'sse_assigned_quality_appraisals_article_fetch_error';

export const SSE_ASSIGNED_LINKING_STUDIES_ARTICLE_QUEUE = 'sse_assigned_linking_studies_queue';
export const SSE_ASSIGNED_LINKING_STUDIES_ARTICLE_QUEUE_ERROR = 'sse_assigned_linking_studies_queue_error';

export const SSE_ASSIGNED_PRESENTATION_DETAILS_ARTICLE_QUEUE = 'sse_assigned_presentation_details_queue';
export const SSE_ASSIGNED_PRESENTATION_DETAILS_QUEUE_ARTICLE_ERROR = 'sse_assigned_presentation_details_queue_error';
