sudo: required
services:
  - docker

before_install:
  - docker build -t sakksoftware/hsse-admin-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sakksoftware/hsse-admin-client-test npm test -- --coverage

after_success:
  - docker build -t sakksoftware/hsse-admin-client ./client
  - docker build -t sakksoftware/hsse-nginx ./nginx
  - docker build -t sakksoftware/hsse-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sakksoftware/hsse-admin-client
  - docker push sakksoftware/hsse-nginx
  - docker push sakksoftware/hsse-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: hsse-project-staging
  env: HsseProjectStaging-env
  bucket_name: elasticbeanstalk-us-east-1-566498504664
  bucket_path: hsse-project-staging
  on:
    branch: master
  access_key_id: $AWS_ELB_ACCESS_KEY
  secret_access_key:
    secure: $AWS_ELB_SECRET_KEY