FROM node:alpine

RUN apk update \
    && apk upgrade \
    && apk add git

RUN npm install -g react-app-rewired

WORKDIR '/app'

COPY ./package.json ./

RUN npm install --unsafe-perm

COPY ./ ./

EXPOSE 3000

CMD ["npm", "run", "start"]